[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dotenvy = "0.15.7"
octocrab = "0.51.0"
poise = "0.6.2"
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
git2 = "0.21.0"
nucleo-matcher = "0.3.1"
walkdir = "2.5.0" 
serde_json = "1.0.150"
serde = { version = "1.0.228", features = ["derive"] }
which = "8.0.2"
