[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
base64 = "0.23.1"
dotenvy = "0.15.7"
flate2 = "1.1.10"
octocrab = "0.54.1"
poise = "0.7.0"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
git2 = "0.21.0"
nucleo-matcher = "0.3.1"
walkdir = "2.5.0" 
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
which = "8.0.6"
